language: python

python:
  - "3.6"

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

before_install:
 - chmod +x travis_build.sh

install: ./travis_build.sh

# command to run tests
script:
 - cd ./tests
 - nosetests --with-cov --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc