language: python

#version
python:
  - "3.6"

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

env:
 - GEOS_VERSION=3.6.2 GDAL_VERSION=2.2.1 PROJ4_VERSION=5.0.1

before_install:
- sudo apt-get update -q

- wget http://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 -O /tmp/geos-${GEOS_VERSION}.tar.bz2 \
    && tar -xf /tmp/geos-${GEOS_VERSION}.tar.bz2 -C /tmp \
    && cd /tmp/geos-${GEOS_VERSION} \
    && ./configure \
    && make \
    && make install \
    && rm -rf /tmp/geos-${GEOS_VERSION}

# - wget http://download.osgeo.org/gdal/${GDAL_VERSION}/gdal-${GDAL_VERSION}.tar.gz -O /tmp/gdal-${GDAL_VERSION}.tar.gz \
#    && tar -x -f /tmp/gdal-${GDAL_VERSION}.tar.gz -C /tmp \
#    && cd /tmp/gdal-${GDAL_VERSION} \
#    && ./configure \
#        --prefix=/usr \
#        --with-python \
#        --with-geos \
#        --with-sfcgal \
#        --with-geotiff \
#        --with-jpeg \
#        --with-png \
#        --with-expat \
#        --with-libkml \
#        --with-openjpeg \
#        --with-pg \
#        --with-curl \
#        --with-spatialite \
#    && make -j $(nproc) \
#    && make install \
#    && rm /tmp/gdal-${GDAL_VERSION} -rf
#
# - wget --no-check-certificate --content-disposition https://github.com/OSGeo/proj.4/releases/download/${PROJ4_VERSION}/proj-${PROJ4_VERSION}.tar.gz -O /tmp/proj-${PROJ4_VERSION}.tar.gz \
#    && tar -xvf /tmp/proj-${PROJ4_VERSION}.tar.gz -C /tmp \
#    && cd /tmp/proj-${PROJ4_VERSION} \
#    && ./configure --prefix=/usr \
#    && make \
#    && make install \
#    && rm -rf /tmp/proj-${PROJ4_VERSION}

 - git clone https://github.com/quanted/requirements_qed.git


install:
  - pip install -r requirements_qed/requirements.txt

# command to run tests
script:
  - nosetests --with-cov --cov pram --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc