language: python

python:
  - "3.6"

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

install: ./travis_build.sh

# command to run tests
script:
  - nosetests --with-cov --cov pram --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc