language: python

#version
python:
  - "3.6"

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

env:
 - GEOS_VERSION=3.6.2 GDAL_VERSION=2.2.1 PROJ4_VERSION=5.0.1

before_install:
 - sudo apt-get update -q
 - git clone https://github.com/quanted/requirements_qed.git


install:
  - pip install -r requirements_qed/requirements.txt

# command to run tests
script:
  - nosetests --with-cov --cov pram --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc