language: python

python:
  - "3.6"

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

before_install:
 - chmod +x travis_build.sh

install: ./travis_build.sh

# command to run tests
script:
 - nosetests --with-cov --cov ./pram_app/tests/test_ubertool_internal.py --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc